version: '3.9'
services:
  rasa:
    build: .
    image: rasa/rasa:2.8.31-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run

  db:
    container_name: mysqlserver
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'vital_signs'
      MYSQL_ROOT_PASSWORD: 'alsharif_2022'

  actionserver:
    image: rasa/rasa-sdk:2.8.4
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
    links:
      - db
    depends_on:
      - db



  duckling:
    image: "rasa/duckling"
    ports:
      - 8000:8000

